### ISSUE TITLE
Not generating classes (1.2.0)

### ISSUE THREAD

**Issue by kaleidografik** [hacknug/tailwindcss-blend-mode#7]
Hi there, is there a compatibility issue with Tailwind 1.2.0? Just installed but classes are not being generated?

**Comment by nlemoine** [comment]
Just submitted a PR that fixes the issue. Waiting for @hacknug to merge it.

**Comment by hacknug** [comment]
Hey! It was actually a documentation issue and nothing related to the v1.2.0 changes. I've updated `README.md` accordingly and will be updating all of my plugins soon to properly support v1.2.0. Please, let me know if this solves your issue and/or you encounter any new ones :+1:

**Comment by kaleidografik** [comment]
Hey @hacknug - thanks. This seems to have fixed the issue and all working as expected. Thanks for creating.

**Comment by hacknug** [comment]
Thank you both for reporting and putting together a fix for it (even though I closed the PR) ❤️
